services:
  backend:
    # build: .
    image: ghcr.io/jullanggit/dieprobezeit-backend:latest
    volumes:
      - ./pdfs:/app/pdfs:ro
      - ./svgs:/app/svgs:ro
      - ./images:/app/images:ro
      - ./kdrive:/app/kdrive:ro
      - ./mng.db:/app/mng.db:rw
    network_mode: "host"
    labels:
      pingoo.service: website
      pingoo.port: "8080"

  caddy:
    image: docker.io/library/caddy:2
    container_name: caddy
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
