//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feedback")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub content: String,
    pub email: Option<String>,
    pub edition_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::edition::Entity",
        from = "Column::EditionId",
        to = "super::edition::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Edition,
}

impl Related<super::edition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Edition.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
